FROM microsoft/dotnet:2.0-sdk-nanoserver-1709 AS build-env
WORKDIR /app

# copy csproj and restore as distinct layers
COPY src/*.cs* ./
RUN dotnet restore

# build
RUN dotnet build
RUN dotnet publish -f netcoreapp2.0 -c Release -o out

FROM microsoft/dotnet:2.0.0-runtime-nanoserver-1709

ARG EXE_DIR=.

WORKDIR /app

COPY --from=build-env /app/out ./

CMD ["dotnet", "iot-edge-modbus.dll"]