FROM microsoft/dotnet:2.2-runtime
WORKDIR /app
COPY /iotedgeModbus/** ./
COPY /iotedgeModbus/libcomWrapper.so /usr/lib/

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "iotedgeModbus.dll"]