FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -r win10-x64 -o out

FROM mcr.microsoft.com/dotnet/core/runtime:2.1.10-nanoserver-1809
WORKDIR /app
COPY --from=build-env /app/out ./

CMD ["iotedgeModbus.exe"]