FROM mcr.microsoft.com/dotnet/core/sdk:2.1 AS build-env
WORKDIR /app

COPY *.csproj ./
RUN dotnet restore -r win10-arm

COPY . ./
RUN dotnet publish -c Release -r win10-arm -o out

FROM mcr.microsoft.com/windows/nanoserver:1809-arm32v7
WORKDIR /app
COPY --from=build-env /app/out ./
CMD ["iotedgeModbus.exe"]